routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');

Auth::routes();

Route::resource('reports', 'ReportController');
Route::post('reports/{id}/update', 'ReportController@update')->name('reports.update.new');

app/Report.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Report extends Model
{

    protected $table = 'reports';
    public $timestamps = true;

    protected $fillable = [
        'title',
        'text',
        'image',
        'user_id',
        'created_at'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ReportController.php
<?php

namespace App\Http\Controllers;

use App\Report;
use Auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;

class ReportController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Auth::id();
        $reports = Report::where('user_id', $id)->latest()->paginate(5);
        return view('reports.index', compact($reports))->withReports($reports)->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('reports.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'text' => 'required',
            'image' => 'required|max:10000|mimes:jpg,jpeg,png'
        ]);

        $data = $request->all();
        $file = $request->file('image');

        $data['image'] = $this->uploadImage($file);
        $data['user_id'] = Auth::id();

        Report::create($data);

        return response()->json(true);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Report  $report
     * @return \Illuminate\Http\Response
     */
    public function edit(Report $report)
    {
        if (!$report->id) {
            return abort(404);
        }

        return view('reports.edit')->withReport($report);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Report  $report
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $report = Report::where('user_id', Auth::id())->find($id);

        if (!$report) {
            return response()->json(['message' => 'not found'], 404);
        }

        $data = $request->all();
        $file = $request->file('image');

        if ($file) {
            $request->validate([
                'title' => 'required',
                'text' => 'required',
                'image' => 'required|max:10000|mimes:jpg,jpeg,png'
            ]);

            File::delete('img/'.$report->image);
            $data['image'] = $this->uploadImage($file);
        } else {
            $request->validate([
                'title' => 'required',
                'text' => 'required',
                'image' => 'required'
            ]);

            if ($request->image != $report->image) {
                return response()->json(['message' => 'Picture not transferred'], 404);
            }
        }

        Report::where('id', $id)->update($data);
        return response()->json(true);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Report  $report
     * @return \Illuminate\Http\Response
     */
    public function destroy(Report $report)
    {
        if (!$report->id || $report->user_id != Auth::id()) {
            return response()->json(['message' => 'not found'], 404);
        }

        $report->delete();

        return response()->json(true);
    }

    /**
     * Upload image
     * @param Illuminate\Http\UploadedFile $image
     * @return string
     */
    private function uploadImage($image)
    {
        $name = date('YmdHis').$image->getClientOriginalName();
        $image->move('img', $name);

        return $name;
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ 'Diary' }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ 'Diary' }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('reports.create') }}">Create report</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/reports/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-danger d-none" role="alert">
                Не все поля заполнены
            </div>
            <form id="report" >
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" placeholder="Enter title">
                </div>
                <div class="form-group">
                    <label for="text">Text</label>
                    <textarea class="form-control" name="text" id="text" cols="30" rows="10"></textarea>
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <img src="" class="preview" width="100" alt="">
                    <input type="file" class="form-control-file" id="image" required>
                </div>
                <button type="button" class="submit btn btn-primary">Submit</button>
            </form>
            <script>
                document.addEventListener("DOMContentLoaded", function() {
                    let token = document.querySelector("input[name='_token']").value;
                    let alert = document.querySelector('.alert');

                    document.querySelector('#image').onchange = function() {
                        let reader = new FileReader();

                        reader.onload = function(e) {
                            document.querySelector('.preview').src = e.target.result;
                        }

                        reader.readAsDataURL(this.files[0]);
                    }
                    
                    document.querySelector('.submit').onclick = async function() {
                        let data = new FormData();
                        let error = false;
                        data.append('title', document.querySelector('#title').value);
                        data.append('text', document.querySelector('#text').value);
                        data.append('image', document.querySelector('#image').files[0] || '');
                        
                        for(let value of data) {
                            if (!value[1]) {
                                document.querySelector('#'+value[0]).classList.remove('is-valid');
                                document.querySelector('#'+value[0]).classList.add('is-invalid');
                                error = true;
                            } else {
                                document.querySelector('#'+value[0]).classList.remove('is-invalid');
                                document.querySelector('#'+value[0]).classList.add('is-valid');
                            }
                        }

                        if (error) {
                            alert.classList.remove('d-none');
                            alert.innerText = 'Не все поля заполнены';
                            return;
                        }
                        let status = 0;
                        alert.classList.add('d-none');

                        let result = await fetch('{{ route("reports.store") }}', {
                            method: 'post',
                            credentials: "same-origin",
                            body: data,
                            headers: {
                                "X-Requested-With": "XMLHttpRequest",
                                'X-CSRF-TOKEN': token
                            }
                        }).then(res => {
                            status = res.status;
                            return res;
                        }).then(res => res.json());

                        if (status != 200) {
                            alert.classList.remove('d-none');
                            alert.innerText = result.message;
                        } else {
                            location.href = "{{ route('reports.index') }}"
                        }
                    }
                });
            </script>
        </div>
    </div>
</div>
@endsection

resources/views/reports/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="alert alert-danger d-none" role="alert">
                Не все поля заполнены
            </div>
            <div class="alert alert-success d-none" role="alert">
                Запись успешно изменена
            </div>
            <form id="report" >
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" placeholder="Enter title" value="{{ $report->title }}">
                </div>
                <div class="form-group">
                    <label for="text">Text</label>
                    <textarea class="form-control" name="text" id="text" cols="30" rows="10">{{ $report->text }}</textarea>
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="hidden" id="preImage" value="{{ $report->image }}">
                    <img src="\img\{{ $report->image }}" class="preview" width="100" alt="">
                    <input type="file" class="form-control-file" id="image" required>
                </div>
                <button type="button" class="submit btn btn-primary">Submit</button>
            </form>
            <script>
                document.addEventListener("DOMContentLoaded", function() {
                    let token = document.querySelector("input[name='_token']").value;
                    let alertDanger = document.querySelector('.alert-danger');
                    let alertSuccess = document.querySelector('.alert-success');

                    document.querySelector('#image').onchange = function() {
                        let reader = new FileReader();

                        reader.onload = function(e) {
                            document.querySelector('.preview').src = e.target.result;
                        }

                        reader.readAsDataURL(this.files[0]);
                    }

                    document.querySelector('.submit').onclick = async function() {
                        alertSuccess.classList.add('d-none');
                        let data = new FormData();
                        let error = false;
                        let preImage = document.querySelector('#preImage').value;
                        data.append('title', document.querySelector('#title').value);
                        data.append('text', document.querySelector('#text').value);
                        data.append('image', document.querySelector('#image').files[0] || preImage);
                        
                        for(let value of data) {
                            if (!value[1]) {
                                document.querySelector('#'+value[0]).classList.remove('is-valid');
                                document.querySelector('#'+value[0]).classList.add('is-invalid');
                                error = true;
                            } else {
                                document.querySelector('#'+value[0]).classList.remove('is-invalid');
                                document.querySelector('#'+value[0]).classList.add('is-valid');
                            }
                        }

                        if (error) {
                            alertDanger.classList.remove('d-none');
                            alertDanger.innerText = 'Не все поля заполнены';
                            return;
                        }
                        let status = 0;
                        alertDanger.classList.add('d-none');

                        let result = await fetch('{{ route("reports.update.new", $report->id) }}', {
                            method: 'POST',
                            credentials: "same-origin",
                            body: data,
                            headers: {
                                "X-Requested-With": "XMLHttpRequest",
                                'X-CSRF-TOKEN': token
                            }
                        }).then(res => {
                            status = res.status;
                            return res;
                        }).then(res => res.json());

                        if (status != 200) {
                            alertDanger.classList.remove('d-none');
                            alertDanger.innerText = result.message;
                        } else {
                            alertSuccess.classList.remove('d-none');
                        }
                    }
                });
            </script>
        </div>
    </div>
</div>
@endsection

resources/views/reports/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @foreach ($reports as $report)
                <div class="card">
                    <div class="card-header">
                        <p class="float-right ml-2"><a class='remove' href="{{ route('reports.destroy', $report->id) }}">Delete</a></p>
                        <p class="float-right"><a href="{{ route('reports.edit', $report->id) }}">Edit</a></p>
                        <p class="float-left">{{ $report->title }}</p>
                    </div>

                    <div class="card-body">
                        <img src="/img/{{ $report->image }}" class="w-100 mb-5" alt="">
                        <p class="text-justify">{{ $report->text }}</p>
                    </div>
                </div>
            @endforeach
            @if (!count($reports))
                <div class="card">
                    <div class="card-body text-center">
                        No records
                    </div>
                </div>
            @endif            
            <div class="d-flex mt-5 justify-content-center">{!! $reports->links() !!}</div>
        </div>
        <script>
            document.addEventListener("DOMContentLoaded", function() {
                let token = document.querySelector("input[name='_token']").value;
                document.querySelectorAll('.remove').forEach(v => v.onclick = async function(e) {
                    e.preventDefault();

                    let result = await fetch(this.href, 
                        {
                            method: 'DELETE',
                            headers: {
                                "X-Requested-With": "XMLHttpRequest",
                                'X-CSRF-TOKEN': token
                            }
                        }).then(res => {
                            status = res.status;
                            return res;
                        }).then(res => res.json());

                    if (status != 200) {
                        alert(result.message);
                    } else {
                        alert('Запись успешно удалена');
                        location.reload();
                    }

                })
            });
        </script>
    </div>
</div>
@endsection